# Generated by Django 5.0.6 on 2025-10-16 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('crop', models.CharField(max_length=100)),
                ('area', models.FloatField()),
                ('others', models.TextField(blank=True)),
                ('seed', models.BooleanField(default=False)),
                ('pesticide', models.BooleanField(default=False)),
                ('fertilizer', models.BooleanField(default=False)),
                ('drip', models.BooleanField(default=False)),
                ('machinery', models.BooleanField(default=False)),
                ('nursery', models.BooleanField(default=False)),
                ('sprayer', models.BooleanField(default=False)),
                ('location', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
