# Generated by Django 5.0.6 on 2025-10-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('crop', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=50)),
                ('seed', models.BooleanField(default=False)),
                ('pesticide', models.BooleanField(default=False)),
                ('fertilizer', models.BooleanField(default=False)),
                ('drip', models.BooleanField(default=False)),
                ('machinery', models.BooleanField(default=False)),
                ('nursery', models.BooleanField(default=False)),
                ('sprayer', models.BooleanField(default=False)),
                ('location', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='FarmerData',
        ),
    ]
