# Generated by Django 5.0.6 on 2025-10-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_farmer_delete_farmerdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='area',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='location',
            field=models.URLField(blank=True, null=True),
        ),
    ]
