# Generated by Django 5.0.6 on 2025-10-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_farmer_area_alter_farmer_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='employee',
            field=models.CharField(choices=[('Employee1', 'Employee1'), ('Employee2', 'Employee2'), ('Employee3', 'Employee3'), ('Employee4', 'Employee4'), ('Employee5', 'Employee5')], default='Employee1', max_length=50),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='location',
            field=models.CharField(max_length=300),
        ),
    ]
