# Generated by Django 5.0.6 on 2025-10-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_farmer_employee_alter_farmer_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='employee',
            field=models.CharField(choices=[('Employee1', 'Employee1'), ('Employee2', 'Employee2'), ('Employee3', 'Employee3'), ('Employee4', 'Employee4'), ('Employee5', 'Employee5')], max_length=50),
        ),
    ]
