# Generated by Django 5.0.6 on 2025-10-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_farmer_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='area',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='employee',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='location',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
