# Generated by Django 5.0.6 on 2025-10-21 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_farmer_area_alter_farmer_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='next_visit',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='others',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='area',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='location',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
