# Generated by Django 5.0.6 on 2025-10-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_farmer_next_visit_farmer_others_alter_farmer_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='area',
            field=models.CharField(max_length=100),
        ),
    ]
