# Generated by Django 5.0.6 on 2025-10-22 02:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_farmer_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='today_date',
            field=models.DateField(default=datetime.date(2024, 1, 1)),
        ),
    ]
