# Generated by Django 6.0.3 on 2026-04-01 18:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_farmer_today_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='today_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
